export const CHARACTERS: string[] = [
  "Messi",
  "Julio Iglesias",
  "Elon Musk",
  "Spiderman",
  "Harry Potter",
  "Shrek",
  "Mario Bros",
  "Batman",
  "Rosalia",
  "Iron Man",
  "Homer Simpson",
  "Pocahontas",
  "Darth Vader",
  "Ibai",
  "El Rey Juan Carlos",
  "Abalos",
  "Iker Jimenez",
  "Cristiano Ronaldo",
  "Gabriel Rufian",
  "Barcenas",
  "Perico Delgado",
  "Arantxa Sanchez Vicario",
  "David Bisbal",
  "Cristiano Ronaldo",
  "Pau Gasol",
  "Rafa Nadal",
  "Fernando Alonso",
  "Marc Marquez",
  "Kobe Bryant",
  "Lady Gaga",
  "Alexia Putellas",
  "Tadej Pogačar",
  "Michael Phelps",
  "Carlos Alcaraz",
  "Lebron James",
  "Michael Jordan",
  "Kylian Mbappé",
  "Cholo Simeone",
  "Bad Bunny",
  "Mickey Mouse",
  "Michael Jackson",
  "Antonio Banderas",
  "La Reina Leticia",
  "Barack Obama",
  "Vladímir Putin",
  "John Lennon",
  "Steve Jobs",
  "Lady Di (Diana de Gales)",
  "Joaquin Sabina",
  "El pato Lucas",
  "Mohammed Ali",
  "Jorge Lorenzo",
  "Matias Prats",
  "Susana Griso",
  "The Rock (Dwayne Johnson)"
];
